name: banana
dim: 2
has_entropy: False

fn:
  _target_: targets.banana.Banana
  dim: ${target.dim}
  p: 10.0
  b: 0.05
  can_sample: True
  sample_bounds: null

# Experiment-specific algorithm parameters (optional overrides)
gfn_non_acyclic:
  init_std: 1.0
  weight_decay: 0.0
  step_size: 1e-3
  bwd_step_size: 1e-3
  logZ_step_size: 1e-1
  init_logZ: 0.
  gamma: 0.1
  reg_coef: 0.0
  num_steps: 100
  eval_max_steps: 500
  loss_type: tb
  logr_clip: -1e5
  huber_delta: null
  grad_clip: 1.0

all:
  batch_size: 2000
  iters: 20000
  milestones: [10000, 15000]
  num_steps: 64
  use_lp: True
  num_hid: 64

